# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-app"
client_id = "e25ee497230a854795530316b4c0b9cc"
application_url = "https://develops-effort-enable-sailing.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://develops-effort-enable-sailing.trycloudflare.com/auth/callback",
  "https://develops-effort-enable-sailing.trycloudflare.com/auth/shopify/callback",
  "https://develops-effort-enable-sailing.trycloudflare.com/api/auth/callback",
  "https://develops-effort-enable-sailing.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-bdc90744.myshopify.com"
